In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [16]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [29]:
import tensorflow as tf
from tensorflow import keras 
from keras.layers import Dense
from keras import Sequential

In [30]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [31]:
model.get_weights()

[array([[-1.1882619, -1.2180009],
        [-1.146453 , -0.474396 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.6302751],
        [ 0.6470965]], dtype=float32),
 array([0.], dtype=float32)]

In [32]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[ 0.1],[0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [33]:
set_weights = model.set_weights(new_weights)

In [34]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [35]:
optimizer = keras.optimizers.SGD(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizer)

In [36]:
model.fit(df.iloc[:,:-1].values,df['lpa'].values,epochs =75)

Epoch 1/75
1/1 [==============================] - 0s 188ms/step - loss: 28.0157
Epoch 2/75
1/1 [==============================] - 0s 3ms/step - loss: 26.9935
Epoch 3/75
1/1 [==============================] - 0s 3ms/step - loss: 25.7924
Epoch 4/75
1/1 [==============================] - 0s 3ms/step - loss: 24.3902
Epoch 5/75
1/1 [==============================] - 0s 3ms/step - loss: 22.7715
Epoch 6/75
1/1 [==============================] - 0s 3ms/step - loss: 20.9333
Epoch 7/75
1/1 [==============================] - 0s 3ms/step - loss: 18.8904
Epoch 8/75
1/1 [==============================] - 0s 3ms/step - loss: 16.6808
Epoch 9/75
1/1 [==============================] - 0s 3ms/step - loss: 14.3678
Epoch 10/75
1/1 [==============================] - 0s 3ms/step - loss: 12.0380
Epoch 11/75
1/1 [==============================] - 0s 3ms/step - loss: 9.7923
Epoch 12/75
1/1 [==============================] - 0s 3ms/step - loss: 7.7305
Epoch 13/75
1/1 [==============================] - 0s 3ms/ste

In [37]:
model.get_weights()

[array([[0.21416374, 0.21416374],
        [0.43670005, 0.43670005]], dtype=float32),
 array([0.02675008, 0.02675008], dtype=float32),
 array([[0.47776118],
        [0.47776118]], dtype=float32),
 array([0.11748473], dtype=float32)]

# classification problem

In [39]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]], columns=['cgpa', 'profile_score', 'lpa'])

In [40]:
df

cgpa  profile_score  lpa
0     8              8    1
1     7              9    1
2     6             10    0
3     5             12    0

In [43]:
model = Sequential()
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [44]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[ 0.1],[0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [45]:
model.set_weights(new_weights)

In [46]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [47]:
optimizer = keras.optimizers.SGD(learning_rate=0.001)
model.compile(loss="binary_crossentropy",optimizer=optimizer)

In [48]:
model.fit(df.iloc[:,:-1].values,df['lpa'].values,epochs =15)

Epoch 1/15
1/1 [==============================] - 0s 234ms/step - loss: 0.6970
Epoch 2/15
1/1 [==============================] - 0s 3ms/step - loss: 0.6970
Epoch 3/15
1/1 [==============================] - 0s 3ms/step - loss: 0.6970
Epoch 4/15
1/1 [==============================] - 0s 3ms/step - loss: 0.6970
Epoch 5/15
1/1 [==============================] - 0s 3ms/step - loss: 0.6970
Epoch 6/15
1/1 [==============================] - 0s 4ms/step - loss: 0.6969
Epoch 7/15
1/1 [==============================] - 0s 3ms/step - loss: 0.6969
Epoch 8/15
1/1 [==============================] - 0s 2ms/step - loss: 0.6969
Epoch 9/15
1/1 [==============================] - 0s 3ms/step - loss: 0.6969
Epoch 10/15
1/1 [==============================] - 0s 5ms/step - loss: 0.6969
Epoch 11/15
1/1 [==============================] - 0s 3ms/step - loss: 0.6969
Epoch 12/15
1/1 [==============================] - 0s 3ms/step - loss: 0.6969
Epoch 13/15
1/1 [==============================] - 0s 3ms/step - loss: 